apiVersion: v1
kind: Pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapKeyRef:
        name: daws
    # - name: course
      # valueFrom:
        # configMapKeyRef:
          # name: daws
          # key: course
    # - name: trainer
      # valueFrom:
        # configMapKeyRef:
          # name: daws
          # key: trainer