apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep 
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  - key: "project"
    operator: "Exists"
    #value: "expense"
    effect: "NoSchedule"
# command: kubectl taint nodes nodename project=exepense:NoSchedule 